title:   ## Connect with Us
description: [Visit our LinkedIn page]([https://www.linkedin.com/company/your-linkedin-handle](https://www.linkedin.com/company/impulse-hochschule-reutlingen))  
theme: minima
header_pages:
  - index.md
  - about.md
  - team.md



