title: IMPULSE
description: IMPULSE is an interdisciplinary student project, developed as part of the Master's program in Power- and Microelectronics. The project focuses on the conception, design, and characterization of a high-performance integrated circuit.
theme: cayman
